### PR TITLE
Brendon kutz - Labs spider progess

### PR DESCRIPTION
**Pull request by ghost**
Gotten base spider built, returns search results of what is asked.

### CODE REVIEW

**Review by kiachoi — CHANGES_REQUESTED** [review]
There are present merge conflicts that need to be resolved.

**Comment by ghost** [comment]
Are these files that I'm missing or files it thinks I'm trying to upload? I got rid of the two possible files I thought could be causing issue

**Comment by mykeal-kenny** [comment]
I'll get with you to resolve these shortly, looks like a simple issue.

**Comment by ghost** [comment]
Fixed @FireInjun saved me

**Review by kiachoi — APPROVED** [review]

**Pull request merged**
